services:
  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin
    volumes:
      - "/mnt/cephfs/tasmoadmin-config:/data"

networks:
  default:
    external: true
    name: main
