services:
  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin
    volumes:
      - "/mnt/cephfs/tasmoadmin-config:/data"
    networks:
      - main

networks:
  main:
    external: true
    name: main
