version: "3"

services:
  shepherd:
    container_name: shepherd
    image: containrrr/shepherd
    restart: unless-stopped
    environment:
      TZ: 'Europe/London'
      SLEEP_TIME: '30m'
      VERBOSE: 'true'
      IGNORELIST_SERVICES: "label=shepherd.autodeploy=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
