services:
  shepherd:
    image: containrrr/shepherd
    environment:
      TZ: 'Europe/London'
      VERBOSE: 'true'
      IGNORELIST_SERVICES: "label=shepherd.autodeploy=false"
      RUN_ONCE_AND_EXIT: "true"
      REGISTRY_USER: "dan1elhughes"
      APPRISE_SIDECAR_URL: apprise:8000
    secrets:
      - shepherd_registry_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 4 * * * *"
        - "swarm.cronjob.skip-running=true"
      replicas: 0
      restart_policy:
        condition: none

  scheduler:
    image: crazymax/swarm-cronjob
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TZ?error}
      - LOG_LEVEL=info
      - LOG_JSON=false

secrets:
  shepherd_registry_password:
    # echo "..." | docker secret create shepherd_registry_password -
    external: true

networks:
  default:
    external: true
    name: main
