services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.68.0
    environment:
      TZ: ${TZ?error}
      GIT_ACCESS_TOKEN: ${DOCO_CD_GIT_ACCESS_TOKEN?error}
      MAX_CONCURRENT_DEPLOYMENTS: 1
      APPRISE_API_URL: http://apprise:8000/notify/3500643eb9f31f99c97b71c6019996194ff58986c849293c1b9d540c6f14116e
      APPRISE_NOTIFY_LEVEL: success
      POLL_CONFIG: |
        - url: https://github.com/dan1elhughes/home-os.git
          reference: refs/heads/master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/cephfs/doco-cd-data:/data
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  default:
    external: true
    name: main
