services:
  tasmoadmin:
    image: ghcr.io/tasmoadmin/tasmoadmin:v5.0.0
    volumes:
      - "/mnt/cephfs/tasmoadmin-config:/data"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tasmoadmin.rule=Host(`tasmoadmin.danhughes.dev`)"
        - "traefik.http.routers.tasmoadmin.entrypoints=websecure"
        - "traefik.http.routers.tasmoadmin.tls=true"
        - "traefik.http.routers.tasmoadmin.tls.certResolver=letsencrypt"
        - "traefik.http.services.tasmoadmin.loadbalancer.server.port=9541"
        - "traefik.swarm.network=main"

  mosquitto:
    image: eclipse-mosquitto:2.0.22
    ports:
      - 1883:1883
    volumes:
      - /mnt/cephfs/mosquitto:/mosquitto
    environment:
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_pub -h localhost -t health/check -m ping -u DVES_USER -P $$MQTT_PASSWORD",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  trmnl-ha:
    image: ghcr.io/usetrmnl/trmnl-ha-amd64:0.7.0
    volumes:
      - /mnt/cephfs/trmnl:/data
    environment:
      - HOME_ASSISTANT_URL=http://homeassistant:8123
      - ACCESS_TOKEN=${TRMNL_ACCESS_TOKEN?error}
      - TZ=${TZ?error}
    ports:
      - 10000:10000
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trmnl-ha.rule=Host(`trmnl.danhughes.dev`)"
        - "traefik.http.routers.trmnl-ha.entrypoints=websecure"
        - "traefik.http.routers.trmnl-ha.tls=true"
        - "traefik.http.routers.trmnl-ha.tls.certResolver=letsencrypt"
        - "traefik.http.services.trmnl-ha.loadbalancer.server.port=10000"
        - "traefik.swarm.network=main"

  homeassistant:
    image: ghcr.io/linuxserver/homeassistant:2026.5.3
    environment:
      - PUID=${PUID?error}
      - PGID=${PGID?error}
      - TZ=${TZ?error}
      - DOCKER_MODS=linuxserver/mods:homeassistant-hacs
    volumes:
      - /mnt/cephfs/homeassistant:/config
    depends_on:
      - mosquitto
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.rule=Host(`home.danhughes.dev`)"
        - "traefik.http.routers.homeassistant.entrypoints=websecure"
        - "traefik.http.routers.homeassistant.tls=true"
        - "traefik.http.routers.homeassistant.tls.certResolver=letsencrypt"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
        - "traefik.swarm.network=main"

networks:
  default:
    external: true
    name: main
